# Setup
title:               Hui Liu
tagline:             'Share my life'
description:         'This is Hui Liu's Blog.'
url:                 https://aloeordown.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hui Liu
  # url:               https://twitter.com/mdo
  email:             huiliu729@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
